# Generated by Django 5.2 on 2025-07-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_due_date_todo_is_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="todo",
            name="description",
        ),
    ]
